env: "local"
http_server:
  address: "0.0.0.0:8081"
  timeout: 3
  read_timeout: 5
  write_timeout: 10
  idle_timeout: 120
grpc:
  port: 50001
  timeout: 5s
token_ttl: 15m
refresh_token_ttl: 720h
reissue_refresh_token_ttl: 24h
master_secret: "master_secret"
hasher:
  memory: 65536
  iterations: 2
  parallelism: 1
  salt_length: 16
  key_length: 32
  worker_limit: 4 #num of hashing workers = num cores (consider 'parallelism' param)
postgres:
  direct:
    host: "db"
    port: 5432
    user: "postgres"
    password: "example"
    database: "auth_db"
    ssl_mode: "disable"
  master:
    host: "pgbouncer-master"
    port: 6432
    user: "postgres"
    password: "example"
    database: "auth_db"
    ssl_mode: "disable"
  replicas:
    host: "pgbouncer-replicas"
    port: 6433
    user: "postgres"
    password: "example"
    database: "auth_db"
    ssl_mode: "disable"
redis:
  addresses:
    - "redis-1:6379"
    - "redis-2:6379"
    - "redis-3:6379"
  operation_timeout: 10ms
caching:
  enabled: false
  app_ttl: 1m
  refresh_token_ttl: 24h
kafka:
  bootstrap_servers: "kafka-1:29092,kafka-2:29092,kafka-3:29092"
  client_id: "auth-producer:"
  topic-user-activity: "auth-user-activity-v1"
  topic-app-key: "auth-app-key-v1"
  batch_num_messages: 1000
  linger_ms: 50
  compression_type: "lz4"
  acks: "all"
  enable_idempotence: true
  retries: 2000
  retry_backoff_ms: 500
  message_timeout_ms: 900000
  socket_keepalive_enable: true
  queue_buffering_max_msgs: 100000
  producer_max_retries: 3
  producer_retry_backoff_ms: 10ms