CREATE TABLE IF NOT EXISTS apps (
    id     SERIAL PRIMARY KEY,
    name   TEXT NOT NULL UNIQUE,
    secret TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
    id        BIGSERIAL PRIMARY KEY,
    email     TEXT NOT NULL UNIQUE,
    pass_hash TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS admins (
    id        BIGINT PRIMARY KEY,
    is_admin  BOOLEAN NOT NULL DEFAULT FALSE
);