INSERT INTO apps (id, name, secret)
VALUES (1, 'testApp', '-----BEGIN PRIVATE KEY-----
MC4CAQAwBQYDK2VwBCIEIDIX990wBqjSUJpPrqG9XNv270LxwwJW7kJurcTugllG
-----END PRIVATE KEY-----')
ON CONFLICT DO NOTHING;

INSERT INTO admins (id, is_admin)
VALUES (1, TRUE)
ON CONFLICT DO NOTHING;